name: "Main"
on: pull_request
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Run Stylelint
        run: npm run lint:styles
      - name: Run Tests
        run: npm test
        env:
          CI: true
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run preview -- --port=3000
          wait-on: http://localhost:3000
          config-file: cypress.config.ts
          browser: chrome
